name: "Install Python Packages"
description: "Install python packages from requirements.txt reference Sabernetic Github"
inputs:
  repos:
    description: "Github Repository"
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/config.sh "${{ inputs.repos }}"
      shell: bash
