name: "Install Python Packages"
description: "Install python packages from requirements.txt. index CodeArtifact"
inputs:
  aws_account_id:
    description: "AWS Account ID"
    required: false
  aws_region:
    description: "AWS Region"
    required: false
  domain:
    description: "CodeArtifact Domain"
    required: false
  repos:
    description: "CodeArtifact Repositories"
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/config.sh ${{ inputs.aws_account_id }} ${{ inputs.aws_region }} ${{ inputs.domain }} "${{ inputs.repos }}"
      shell: bash
