name: "Install Python Packages"
description: "Install python packages"
inputs:
  aws-account-id:
    description: "AWS Account ID"
    required: false
  aws-region:
    description: "AWS Region"
    required: false
  domain:
    description: "CodeArtifact Domain"
    required: false
  repos:
    description: "CodeArtifact Repositories"
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/config.sh ${{ inputs.aws-account-id }} ${{ inputs.aws-region }} ${{ inputs.domain }} ${{ inputs.repos }}
      shell: bash
