name: 'Hello Action'
description: 'Complete some task'
inputs:
  what-to-do:  # id of input
    description: 'What to Do'
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/config.sh ${{ inputs.what-to-do }}
      shell: bash
